spring:
  application:
    name: flight-search

  datasource:
    url: jdbc:postgresql://localhost:5432/flights_search
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080

jwt:
  secret: nzB8bGyyAr2ZVJZoK+p+RdXio64fHqsP5S2tmlU/8oCApTbmWdFJmmtbzdHDIZNsxJ/8GIQn8JQ95ye3oIrqDLhbQRrC8+cm+OtNY5v321SAJbPzzK1dKPPmnO1Uj22VUqF/PdhjAMtkPvX1B0jNnLL0OpRNxew7geN6PkdfLtvM